---
- name: Create default containers 
  docker_container:
    name: "tomcat7"
    image: "consol/tomcat-7.0"
    state: started
    ports:
      - "9050:8080"
    mount: "type:bind,source=/home/user/tomcat-bind,target=/opt/tomcat/webapps"


